trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildJob
  displayName: 'Build Job'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
    
  - script: |
      npm install -g @angular/cli
      npm install
      ng build --configuration production
    displayName: 'npm install and build'
    workingDirectory: '$(Build.SourcesDirectory)'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/deck/'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'