version: '3'


services:
  chat-db:
    image: postgres:14.11
    restart: always
    ports:
      - "5403:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_CHAT}
      POSTGRES_DB: ${DB_NAME_CHAT}
    container_name: deckexcdbchat
    volumes:
      - ./postgres_chat:/var/lib/postgresql/data
